### ISSUE TITLE
Variable extra raiz

### ISSUE THREAD

**Issue by Fabro97** [Fabro97/TareaFra#1]
Hace una variable para guardar el valor de la raiz cuadrada una sola vez.
Porque la vas a tener que  usar 2 veces y evitas escribir ese choclo.
Resumiendo hace una variable mas para guardar el resultado de la raiz del numero

**Comment by flezzi09** [comment]
y como le pongo ese valor a raiz?

**Comment by flezzi09** [comment]
eso resuelve el tema del buscar si el numero es primo aal principio?
